---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./repositories.yaml
  - ./calibre
  - ./immich
  - ./jellyfin
  - ./navidrome
  - ./prowlarr
  - ./profilarr
  - ./radarr
  - ./readarr
  - ./slskd
  - ./slskd-importer
  - ./sonarr
  - ./transmission
