---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./repositories.yaml
  - ./cloudflare-ddns
  - ./foregjo
  - ./home-assistant
  - ./karakeep
  - ./mealie
  - ./miniflux
  - ./mqtt
  - ./music-assistant
  - ./redlib
  - ./renovate
  - ./searxng
  - ./syncthing
  - ./zigbee2mqtt
