---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - discord.yaml
  - release.yaml
configMapGenerator:
  - name: slskd-importer-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
